### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by airon90** [gen2brain/bukanir#3]
How to translate the app?

**Comment by gen2brain** [comment]
There is no support for translations currently.

**Comment by Airon90** [comment]
Do you plan to add support to translations?

**Comment by gen2brain** [comment]
I will add support, probably in next release, it will use QTranslator and .ts files.

**Comment by Airon90** [comment]
When you start working on it, please ping me ;)

**Comment by gen2brain** [comment]
Hey, I just added support for translations, https://github.com/gen2brain/bukanir/tree/master/desktop/qml/i18n . You can use Qt Linguist to help you translate file.
