### ISSUE TITLE
subtitiles language.

### ISSUE THREAD

**Issue by Drfrag** [gen2brain/bukanir#6]
Even after chosing subtitles language (portuguese), the subtitles downloaded are on english.
Is there a wright way to do that?
Thanks.

**Comment by gen2brain** [comment]
If other language subtitles are not found on opensubs, podnapisi and subscene, it will search again for english subtitles.

**Comment by Drfrag** [comment]
I am using Mac OSX 10.12.3 
All subtitles are  on english. And color is always white.
Tried to use with spanish, chinese, japanese languages and red and yellow color, but always get english subs with white color.
